# GET http://localhost:8080/api/pokemons/concurrent?type=even&items=4&items_per_workers=2

# GET http://localhost:8080/api/pokemons/source?limit=10&offset=300

# GET http://localhost:8080/api/pokemons/310

# GET http://localhost:8080/api/pokemons

# GET http://localhost:8080/health-check
